import { FC, useEffect } from 'react'
import History from '../../components/History/History'

const BattlesScreen: FC = () => {

    useEffect(() => {
        window.scrollTo(0, 0)
    }, [])

    return (
        <main>
            <History
                title='Qurtuluş Savaşı'
                text='Türk ordusunun büyük bir azimle savaştığı bir cephe olan Kurtuluş Savaşı Cephesi 31 Mart 1921 senesine kadar sürmüş ve çok kanlı geçmiştir. Mustafa Kemal Bu savaş sonrası `milletin makus talihini yenen bir savaş olmuştur` şeklinde bir ifade ile bu savaşın önemini anlatmıştır.'
                img='https://www.gelincanlar.com/wp-content/uploads/2019/10/ataturk-askerlik-yillari.jpg'
            />
            <History
                title='Çanakkale Savaşı'
                text='Birinci Dünya Savaşı esnasında Osmanlı Devleti’nin savaştığı en güçlü cephelerden bir tanesi Çanakkale Cephesi olmuştur. Birinci Dünya Savaşı’nın en kanlı cephelerinden birisi olan Çanakkale Cephesi’nde Rusya’ya yardım etmek isteyen İngiltere ve Fransa ile savaşılmıştır. Fransa ve İngiltere’nin Rusya’ya yardım etmek istemesinin altında yatan neden ise Rusya’nın zayıflayan ekonomisini güçlendirerek Rusya’nın Osmanlı Devleti’ni savaş dışı bırakmasını sağlayabilmekti. Bu amaçlar ile Fransa ve İngiltere Çanakkale Cephesi’ne bir saldırı düzenlediler. İlk olarak deniz savaşları ile başlayan Çanakkale Savaşı İngiliz ve Fransız’ların Çanakkale Boğazı’ndan geçiş sırasında ağır kayıplar vermesi ile ilerledi. Denizde ağır kayıplar veren bu devletler Gelibolu’ya asker çıkararak Osmanlı Devleti’ne karadan saldırmayı planlamışlarsa da Gelibolu’da Mustafa Kemal Atatürk’ün komutasındaki Türk ordusu, bu saldırıyı yine denizde olduğu gibi başarılı bir şekilde önlemeyi başarmıştır. Gelibolu Yarımadası’nda Mustafa Kemal Atatürk’ün düşman askerlerine karşı gösterdiği başarısı onun albaylık rütbesine yükselmesini sağlamıştır. Bu savaşlar sırasında yaklaşık olarak 253.000 subay, er ve erbaş şehit olmuştur. Düşman orduları Fransız ve İtalyanlar ise yine aynı şekilde Türkler kadar çok kayıplar vermişler ve 1915 senesin 20 Aralık tarihinde Anafartalar ve Arıburnu’ndan kesin olarak çekilmişlerdir.'
                img='https://foto.haberler.com/haber/2021/02/03/canakkale-savasi-tarihi-canakkale-savasi-kisaca-13906031_5274_amp.jpg'
            />
            <History
                title='Doğu (Kafkas) Cephesi'
                text='Birinci Dünya Savaşı esnasında Osmanlı Devleti’nin savaştığı en güçlü cephelerden bir tanesi Çanakkale Cephesi olmuştur. Birinci Dünya Savaşı’nın en kanlı cephelerinden birisi olan Çanakkale Cephesi’nde Rusya’ya yardım etmek isteyen İngiltere ve Fransa ile savaşılmıştır. Fransa ve İngiltere’nin Rusya’ya yardım etmek istemesinin altında yatan neden ise Rusya’nın zayıflayan ekonomisini güçlendirerek Rusya’nın Osmanlı Devleti’ni savaş dışı bırakmasını sağlayabilmekti. Bu amaçlar ile Fransa ve İngiltere Çanakkale Cephesi’ne bir saldırı düzenlediler. İlk olarak deniz savaşları ile başlayan Çanakkale Savaşı İngiliz ve Fransız’ların Çanakkale Boğazı’ndan geçiş sırasında ağır kayıplar vermesi ile ilerledi. Denizde ağır kayıplar veren bu devletler Gelibolu’ya asker çıkararak Osmanlı Devleti’ne karadan saldırmayı planlamışlarsa da Gelibolu’da Mustafa Kemal Atatürk’ün komutasındaki Türk ordusu, bu saldırıyı yine denizde olduğu gibi başarılı bir şekilde önlemeyi başarmıştır. Gelibolu Yarımadası’nda Mustafa Kemal Atatürk’ün düşman askerlerine karşı gösterdiği başarısı onun albaylık rütbesine yükselmesini sağlamıştır. Bu savaşlar sırasında yaklaşık olarak 253.000 subay, er ve erbaş şehit olmuştur. Düşman orduları Fransız ve İtalyanlar ise yine aynı şekilde Türkler kadar çok kayıplar vermişler ve 1915 senesin 20 Aralık tarihinde Anafartalar ve Arıburnu’ndan kesin olarak çekilmişlerdir.'
                img='https://iasbh.tmgrup.com.tr/5da3f2/650/344/0/0/720/377?u=https://isbh.tmgrup.com.tr/sbh/2020/12/13/1607858251827.jpg'
            />
            <History
                title='Suriye-Filistin Cephesi'
                text='Birinci Dünya Savaşı esnasında Osmanlı Devleti’nin savaştığı en güçlü cephelerden bir tanesi Çanakkale Cephesi olmuştur. Birinci Dünya Savaşı’nın en kanlı cephelerinden birisi olan Çanakkale Cephesi’nde Rusya’ya yardım etmek isteyen İngiltere ve Fransa ile savaşılmıştır. Fransa ve İngiltere’nin Rusya’ya yardım etmek istemesinin altında yatan neden ise Rusya’nın zayıflayan ekonomisini güçlendirerek Rusya’nın Osmanlı Devleti’ni savaş dışı bırakmasını sağlayabilmekti. Bu amaçlar ile Fransa ve İngiltere Çanakkale Cephesi’ne bir saldırı düzenlediler. İlk olarak deniz savaşları ile başlayan Çanakkale Savaşı İngiliz ve Fransız’ların Çanakkale Boğazı’ndan geçiş sırasında ağır kayıplar vermesi ile ilerledi. Denizde ağır kayıplar veren bu devletler Gelibolu’ya asker çıkararak Osmanlı Devleti’ne karadan saldırmayı planlamışlarsa da Gelibolu’da Mustafa Kemal Atatürk’ün komutasındaki Türk ordusu, bu saldırıyı yine denizde olduğu gibi başarılı bir şekilde önlemeyi başarmıştır. Gelibolu Yarımadası’nda Mustafa Kemal Atatürk’ün düşman askerlerine karşı gösterdiği başarısı onun albaylık rütbesine yükselmesini sağlamıştır. Bu savaşlar sırasında yaklaşık olarak 253.000 subay, er ve erbaş şehit olmuştur. Düşman orduları Fransız ve İtalyanlar ise yine aynı şekilde Türkler kadar çok kayıplar vermişler ve 1915 senesin 20 Aralık tarihinde Anafartalar ve Arıburnu’ndan kesin olarak çekilmişlerdir.'
                img='https://sozcuo01.sozcucdn.com/wp-content/uploads/2018/07/ataturk-sinan-meydan.jpg'
            />
            <History
                title='Sakarya Savaşı'
                text='Birinci Dünya Savaşı esnasında Osmanlı Devleti’nin savaştığı en güçlü cephelerden bir tanesi Çanakkale Cephesi olmuştur. Birinci Dünya Savaşı’nın en kanlı cephelerinden birisi olan Çanakkale Cephesi’nde Rusya’ya yardım etmek isteyen İngiltere ve Fransa ile savaşılmıştır. Fransa ve İngiltere’nin Rusya’ya yardım etmek istemesinin altında yatan neden ise Rusya’nın zayıflayan ekonomisini güçlendirerek Rusya’nın Osmanlı Devleti’ni savaş dışı bırakmasını sağlayabilmekti. Bu amaçlar ile Fransa ve İngiltere Çanakkale Cephesi’ne bir saldırı düzenlediler. İlk olarak deniz savaşları ile başlayan Çanakkale Savaşı İngiliz ve Fransız’ların Çanakkale Boğazı’ndan geçiş sırasında ağır kayıplar vermesi ile ilerledi. Denizde ağır kayıplar veren bu devletler Gelibolu’ya asker çıkararak Osmanlı Devleti’ne karadan saldırmayı planlamışlarsa da Gelibolu’da Mustafa Kemal Atatürk’ün komutasındaki Türk ordusu, bu saldırıyı yine denizde olduğu gibi başarılı bir şekilde önlemeyi başarmıştır. Gelibolu Yarımadası’nda Mustafa Kemal Atatürk’ün düşman askerlerine karşı gösterdiği başarısı onun albaylık rütbesine yükselmesini sağlamıştır. Bu savaşlar sırasında yaklaşık olarak 253.000 subay, er ve erbaş şehit olmuştur. Düşman orduları Fransız ve İtalyanlar ise yine aynı şekilde Türkler kadar çok kayıplar vermişler ve 1915 senesin 20 Aralık tarihinde Anafartalar ve Arıburnu’ndan kesin olarak çekilmişlerdir.'
                img='https://tssf.gov.tr/wp-content/uploads/2021/09/Sakarya-Meydan-Muharebesinin-100uncu-yil-donumu.jpg '
            />
            <History
                title='Trablusgarp Savaş'
                text='Birinci Dünya Savaşı esnasında Osmanlı Devleti’nin savaştığı en güçlü cephelerden bir tanesi Çanakkale Cephesi olmuştur. Birinci Dünya Savaşı’nın en kanlı cephelerinden birisi olan Çanakkale Cephesi’nde Rusya’ya yardım etmek isteyen İngiltere ve Fransa ile savaşılmıştır. Fransa ve İngiltere’nin Rusya’ya yardım etmek istemesinin altında yatan neden ise Rusya’nın zayıflayan ekonomisini güçlendirerek Rusya’nın Osmanlı Devleti’ni savaş dışı bırakmasını sağlayabilmekti. Bu amaçlar ile Fransa ve İngiltere Çanakkale Cephesi’ne bir saldırı düzenlediler. İlk olarak deniz savaşları ile başlayan Çanakkale Savaşı İngiliz ve Fransız’ların Çanakkale Boğazı’ndan geçiş sırasında ağır kayıplar vermesi ile ilerledi. Denizde ağır kayıplar veren bu devletler Gelibolu’ya asker çıkararak Osmanlı Devleti’ne karadan saldırmayı planlamışlarsa da Gelibolu’da Mustafa Kemal Atatürk’ün komutasındaki Türk ordusu, bu saldırıyı yine denizde olduğu gibi başarılı bir şekilde önlemeyi başarmıştır. Gelibolu Yarımadası’nda Mustafa Kemal Atatürk’ün düşman askerlerine karşı gösterdiği başarısı onun albaylık rütbesine yükselmesini sağlamıştır. Bu savaşlar sırasında yaklaşık olarak 253.000 subay, er ve erbaş şehit olmuştur. Düşman orduları Fransız ve İtalyanlar ise yine aynı şekilde Türkler kadar çok kayıplar vermişler ve 1915 senesin 20 Aralık tarihinde Anafartalar ve Arıburnu’ndan kesin olarak çekilmişlerdir.'
                img='https://www.murselcavus.com/wp-content/files/2019/07/TRABLUSGARP.png'
            />
            <History
                title='İkinci Balkan Savaşı'
                text='Balkan Savaşları sırasında dört ülkeye karşı birden savaşan Osmanlı Devleti, Balkan Savaşları’nı kaybetmiştir. Bu savaş sonrası Londra Antlaşması imzalanmıştır. Bu antlaşmaya göre, Osmanlı Devleti Balkan ve Trakya topraklarını kaybetmiştir. İkinci Balkan Savaşı’da Balkan Devletleri’nin kazandıkları toprakları kendi aralarında paylaşamamaları sonucu çıkmıştır. Bu sırada Trablusgarp’ta ordu komutasında görev yapan Mustafa Kemal Atatürk ise bu savaşın sonra ermesi ile İstanbul’a dönmüş ve İkinci Balkan Savaşı’nın patlak vermesi ile Gelibolu’da yeniden görevlendirilmiştir. İkinci Balkan Savaşı sırasında Trakya’da gösterdiği başarısından dolayı Mustafa Kemal Atatürk Sofya ateşeliğine atanmıştır. Osmanlı Devleti’nin Birinci Balkan Savaşı ile Gelibolu ve Trakya’da kaybettiği toprakların bir kısmını İkinci Balkan Savaşı ile geri kazanmasında Mustafa Kemal’in askeri başarısı yine etkili olmuştur.'
                img='https://avim.org.tr/images/uploads/Bulten/ii-balkan-savasi-ni-bitiren-bukres-anlasmasi-10-agustos-1913-h258685-030e8.jpg'
            />
            <History
                title='Arnavutluk İsyanı'
                text='Birinci Dünya Savaşı esnasında Osmanlı Devleti’nin savaştığı en güçlü cephelerden bir tanesi Çanakkale Cephesi olmuştur. Birinci Dünya Savaşı’nın en kanlı cephelerinden birisi olan Çanakkale Cephesi’nde Rusya’ya yardım etmek isteyen İngiltere ve Fransa ile savaşılmıştır. Fransa ve İngiltere’nin Rusya’ya yardım etmek istemesinin altında yatan neden ise Rusya’nın zayıflayan ekonomisini güçlendirerek Rusya’nın Osmanlı Devleti’ni savaş dışı bırakmasını sağlayabilmekti. Bu amaçlar ile Fransa ve İngiltere Çanakkale Cephesi’ne bir saldırı düzenlediler. İlk olarak deniz savaşları ile başlayan Çanakkale Savaşı İngiliz ve Fransız’ların Çanakkale Boğazı’ndan geçiş sırasında ağır kayıplar vermesi ile ilerledi. Denizde ağır kayıplar veren bu devletler Gelibolu’ya asker çıkararak Osmanlı Devleti’ne karadan saldırmayı planlamışlarsa da Gelibolu’da Mustafa Kemal Atatürk’ün komutasındaki Türk ordusu, bu saldırıyı yine denizde olduğu gibi başarılı bir şekilde önlemeyi başarmıştır. Gelibolu Yarımadası’nda Mustafa Kemal Atatürk’ün düşman askerlerine karşı gösterdiği başarısı onun albaylık rütbesine yükselmesini sağlamıştır. Bu savaşlar sırasında yaklaşık olarak 253.000 subay, er ve erbaş şehit olmuştur. Düşman orduları Fransız ve İtalyanlar ise yine aynı şekilde Türkler kadar çok kayıplar vermişler ve 1915 senesin 20 Aralık tarihinde Anafartalar ve Arıburnu’ndan kesin olarak çekilmişlerdir.'
                img='https://upload.wikimedia.org/wikipedia/commons/9/9a/Shkup1912.jpg'
            />
            <History
                title='31 Mart Vakası'
                text='İkinci Meşrutiyetin ilanından sonra İstanbul’da oluşan yönetime karşı oluşturulmuş çok büyük çapta bir ayaklanmadır. Toplamda 13 gün sürmüştür. En başta askeri bir yapı ile başlayan ayaklanma daha sonra dini kesimlerinden araya girmesi ile dini bir boyut kazanmıştır. İstanbul’da hükümetin istifa etmesini sağlayan isyan ile isyancı askerler 7 gün boyunca İstanbul’u kuşatmışlardır. Bu askerlerin hangi amaç ile isyan ettikleri ve bu isyanın planlı ya da bilinçli bir isyan olup olmadığı hala bilinmemektedir. 31 Mart faciasının birebir içerisinde bulunan ve olayları gözlemleyen Atatürk, Orgeneral İzzettin Çalışlar ile isyan eden askerlere karşı savaşmışlardır. Atatürk’ün oluşturmuş olduğu Hareket Ordusu’nun başarısı ve 31 Mart Vakasında yaşananlar daha sonra Atatürk’ün dilinden Ulusal Gazetesinden yayımlanmıştır.'
                img='https://www.gelincanlar.com/wp-content/uploads/2019/10/ataturk-savaslari.jpg'
            />
        </main>
    )
}

export default BattlesScreen
